let stockCafe = [
    {id: 1, nombre: "ALTURA 1 - Blend.", tipo: "cafe", desc: "Se caracteriza por su dulzor y su prolongado retrogusto. Un café con un perfil de sabor redondo y con acidez muy balanceada. Complejo y con cuerpo.", precio: 2400, img: 'pblest/images/BLEND.jpg'},
    {id: 2, nombre: "COLOMBIA, San Lorenzo.", tipo: "cafe", desc: "Un café delicado, floral y sumamente complejo que siempre invita a una taza más.", precio: 2200, img: 'pblest/images/COLOMBIAsl.jpg'},   
    {id: 3, nombre: "COLOMBIA, Cartago.", tipo: "cafe", desc: "Un hallazgo raro y codiciado, un híbrido que se destaca en todo sentido desde el llamativo color rosa de sus frutos hasta su sabor notablemente dulce.", precio: 1800, img: 'pblest/images/COLOMBIAca.jpg'},
    {id: 4, nombre: "ETIOPIA, Shara.", tipo: "cafe", desc: "Tan exótico como su origen, es un blend de varietales reliquia locales. Con cuerpo sedoso y acidez vibrante, se destaca por sus delicadas notas cítricas que recuerdan a la lima y al quinoto, también a los frutos amarillos.", precio: 2200, img: 'pblest/images/ETIOPIAsh.jpg'},
    {id: 5, nombre: "ETIOPIA, Uraga.", tipo: "cafe", desc: "Un café con atributos balanceados que abrazan el paladar. Su retrogusto jugoso, acidez vibrante y cuerpo sedoso definen una experiencia completa y agradable.", precio: 2300, img: 'pblest/images/ETIOPIAur.jpg'},
    {id: 6, nombre: "GUATEMALA, Huehuetenango.", tipo: "cafe", desc: "Es un cafe particularmente tostado, con lotes de avellanas, toffee y caramelo. Una de las tazas más sabrosas del mundo y no por nada te decimos que te roba una sonrisa.", precio: 1800, img: 'pblest/images/GUATEMALAhu.jpg'},
    {id: 7, nombre: "KENIA, Kirinyaga", tipo: "cafe", desc: "Un café particularmente mantecoso en fragancia, en boca presenta notas a manzana roja, mandarina, caramelo y miel de maple, con un retrogusto jugoso y prolongado. Se destaca por su acidez crujiente, vibrante y su cuerpo almibarado y redondo.", precio: 2200, img: 'pblest/images/KENIAki.jpg'},
    {id: 8, nombre: "NICARAGUA, Jinotega.", tipo: "cafe", desc: "Es un café que cautiva por su complejidad. Dulce y cremoso, con marcadas notas a frutos rojos. Una sensaciòn aromatica floral que lo convierte en ùnico.", precio: 1600, img: 'pblest/images/NICARAGUAji.jpg'},
    {id: 9, nombre: "NICARAGUA, Matagalpa.", tipo: "cafe", desc: "Un café natural, exótico y complejo. Intensidad en fragancias a avellanas y aroma a frutos rojos. En frío presenta un marcado aroma a rosa mosqueta. Su sabor fresco y frutal, fondo sutil a lima y posgusto a menta y peperina.", precio: 1800, img: 'pblest/images/NICARAGUAma.jpg'},
    {id: 10, nombre: "PERU, Amazonas.", tipo: "cafe", desc: "Es un lote jugoso, con cuerpo cremoso y notas cítricas que recuerdan al té de limón. Dulce, con un retrogusto limpio y acidez vibrante, expresa su mejor versión en métodos de filtro.", precio: 2100, img: 'pblest/images/PERUama.jpg'},
]


